name: orcamento-execucao-dev

services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    ports:
      - "5432:5432"
    container_name: orcamento-execucao_db_dev

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: orcamento-execucao_backend_dev
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: ./backend
          action: rebuild

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: orcamento-execucao_frontend_dev
    command: yarn serve
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"

volumes:
  pgdata:
