services:
  db:
    image: postgres:15
    container_name: orcamento-execucao_db
    environment:
      POSTGRES_DB: orcamento-execucao_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: orcamento-execucao_backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: orcamento-execucao_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata: