# Generated by Django 5.1.4 on 2025-04-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_detailed_nature_project_funding_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_compensation_executed',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='total_compensation_expected',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='total_compensation_overdue',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='total_compensation_pending',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
