# Generated by Django 5.1.4 on 2025-05-31 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_total_fcte_amount_expected'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='processo_sei',
            field=models.CharField(max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Must be in format ddddd.dddddd/YYYY-MM', regex='^\\d{5}\\.\\d{6}/\\d{4}-\\d{2}$')]),
        ),
    ]
