# Generated by Django 5.1.4 on 2025-05-31 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_installment_processo_sei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='processo_sei',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Must be in format ddddd.dddddd/YYYY-MM', regex='^\\d{5}\\.\\d{6}/\\d{4}-\\d{2}$')]),
        ),
    ]
