name: Deploy Docs

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Deploy Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install mkdocs-material

      - name: Build and deploy
        run: mkdocs gh-deploy --force
